"""Initial migration

Revision ID: 7d6e5274f40e
Revises: 
Create Date: 2025-09-06 17:48:17.429313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d6e5274f40e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('face_embedding', sa.JSON(), nullable=True),
    sa.Column('bank_account_no', sa.String(length=50), nullable=False),
    sa.Column('ifsc_code', sa.String(length=20), nullable=False),
    sa.Column('branch_name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('PENDING_APPROVAL', 'PENDING_PAYMENT', 'ACTIVE', 'REJECTED', name='userstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('image_blob', sa.BLOB(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_phone_number'), 'users', ['phone_number'], unique=True)
    op.create_table('access_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('access_time', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_access_logs_id'), 'access_logs', ['id'], unique=False)
    op.create_table('lockers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('locker_number', sa.String(length=20), nullable=False),
    sa.Column('pin_hash', sa.String(length=255), nullable=False),
    sa.Column('subscription_plan', sa.Enum('BASIC', 'SILVER', 'GOLD', 'PLATINUM', name='subscriptionplan'), nullable=False),
    sa.Column('tenure_years', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('locker_number'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_lockers_id'), 'lockers', ['id'], unique=False)
    op.create_table('nominees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nominee_name', sa.String(length=100), nullable=False),
    sa.Column('user_relationship', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nominees_id'), 'nominees', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_nominees_id'), table_name='nominees')
    op.drop_table('nominees')
    op.drop_index(op.f('ix_lockers_id'), table_name='lockers')
    op.drop_table('lockers')
    op.drop_index(op.f('ix_access_logs_id'), table_name='access_logs')
    op.drop_table('access_logs')
    op.drop_index(op.f('ix_users_phone_number'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
